#pragma once

#include "tensorutils_asc.h"

using namespace AscendC;

namespace mbsmxfp4_detail {

__aicore__ inline void mbsmxfp4_kernel_vec_f32(GM_ADDR x_, GM_ADDR y_, GM_ADDR workspace, int rows, int cols) {
    (void)workspace;
    TPipe pipe;
    TPipe* pipe_ptr = GetTPipePtr();
    int _offset = 0;
    DEvent<PIPE_V, PIPE_MTE2, true> _tmp_devent_valid_ubin_0;
    DEvent<PIPE_MTE2, PIPE_V, false> _tmp_devent_ready_ubin_0;
    DEvent<PIPE_V, PIPE_MTE3, false> _tmp_devent_ready_ubout_0;
    DEvent<PIPE_MTE3, PIPE_V, true> _tmp_devent_valid_ubout_0;
    GlobalTensor<float> x; x.SetGlobalBuffer((__gm__ float*) x_);
    GlobalTensor<float> y; y.SetGlobalBuffer((__gm__ float*) y_);

    int macros_per_row = ((cols) / (128));
    int total_macros = macros_per_row * rows;
    GlobalTensor<float> x_macro = x;
    GlobalTensor<float> y_macro = y;
    DBuff<float, TPosition::VECCALC> x_float_buf; x_float_buf.Init(33 * 128);
    DBuff<float, TPosition::VECCALC> y_float_buf; y_float_buf.Init(33 * 128);
    LocalTensor<float> macro_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> q_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> neg_q_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> const_full = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> macro_left_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_right_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_amax_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_safe_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_recip_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_factor_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_factor_bcast = AllocateLocalTensor<TPosition::VECCALC, float>(32 * 8);
    LocalTensor<float> group_amax_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_input_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_exp_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_bcast = AllocateLocalTensor<TPosition::VECCALC, float>(32 * 8);
    LocalTensor<uint8_t> scalar_flag = AllocateLocalTensor<TPosition::VECCALC, uint8_t>(1 * 64);
    LocalTensor<uint8_t> group_flag = AllocateLocalTensor<TPosition::VECCALC, uint8_t>(33 * 512);
    LocalTensor<float> one_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> six_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> min_scale_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<int> exp_mask_i32 = AllocateLocalTensor<TPosition::VECCALC, int>(1 * 64);
    int n_tiles = CeilDiv(total_macros, 32);
    int tiles_per_core = CeilDiv(n_tiles, GetBlockNum());
    int tile_begin = tiles_per_core * GetBlockIdx();
    int tile_end = Min(tile_begin + tiles_per_core, n_tiles);
    Duplicate<float, false>(one_s, (float)1.0f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<float, false>(six_s, (float)6.0f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<float, false>(min_scale_s, (float)5.877471754111438e-39f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<int, false>(exp_mask_i32, (int)2139095040, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    for (int tile_idx = tile_begin; tile_idx < tile_end; tile_idx += 1) {
        int macro0 = 32 * tile_idx;
        int valid_macros = Min(32, -macro0 + total_macros);
        _tmp_devent_valid_ubin_0.wait();
        GM2UBPAD(x_float_buf.get(tile_idx), x_macro[macro0 * 128], valid_macros, 512, 0, 0);
        _tmp_devent_ready_ubin_0.set();
        _tmp_devent_ready_ubin_0.wait();
        _tmp_devent_valid_ubout_0.wait();
        LocalTensor<float> x_float = x_float_buf.get(tile_idx);
        LocalTensor<float> y_float = y_float_buf.get(tile_idx);
        Abs<float, false>(macro_abs, x_float, MASK_PLACEHOLDER, 2 * valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        WholeReduceMax<float, false>(macro_left_s, macro_abs, MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
        WholeReduceMax<float, false>(macro_right_s, macro_abs[64], MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
        PipeBarrier<PIPE_V>();
        Max<float, false>(macro_amax_s, macro_left_s, macro_right_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        UB2UB(macro_safe_s, macro_amax_s, 1, CeilDiv(valid_macros, 8), CeilDiv(64 - valid_macros, 8), CeilDiv(64 - valid_macros, 8));
        PipeBarrier<PIPE_V>();
        CompareScalar<float, uint8_t, false>(scalar_flag, macro_safe_s, (float)0.0f, CMPMODE::NE, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {1, 1, 8, 8});
        PipeBarrier<PIPE_V>();
        SetCmpMask(one_s);
        PipeBarrier<PIPE_V>();
        Select(macro_safe_s, scalar_flag, macro_safe_s, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Div<float, false>(macro_recip_s, six_s, macro_safe_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        LocalTensor<uint16_t> macro_recip_u16 = macro_recip_s.ReinterpretCast<uint16_t>();
        LocalTensor<uint16_t> macro_factor_u16 = macro_factor_s.ReinterpretCast<uint16_t>();
        LocalTensor<uint16_t> macro_exp_mask_u16 = exp_mask_i32.ReinterpretCast<uint16_t>();
        LocalTensor<int> macro_recip_i32 = macro_recip_s.ReinterpretCast<int>();
        And<uint16_t, false>(macro_factor_u16, macro_recip_u16, macro_exp_mask_u16, MASK_PLACEHOLDER, CeilDiv(2 * valid_macros, 128), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        PipeBarrier<PIPE_V>();
        Div<float, false>(macro_safe_s, macro_recip_s, macro_factor_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Adds<float, false>(macro_safe_s, macro_safe_s, (float)-1.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Muls<float, false>(macro_safe_s, macro_safe_s, (float)256.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Cast<int, float, false>(macro_recip_i32, macro_safe_s, RoundMode::CAST_TRUNC, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint16_t)8, (uint16_t)8});
        PipeBarrier<PIPE_V>();
        Cast<float, int, false>(macro_safe_s, macro_recip_i32, RoundMode::CAST_ROUND, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint16_t)8, (uint16_t)8});
        PipeBarrier<PIPE_V>();
        Muls<float, false>(macro_safe_s, macro_safe_s, (float)0.00390625f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Adds<float, false>(macro_factor_s, macro_safe_s, (float)1.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        CompareScalar<float, uint8_t, false>(scalar_flag, macro_amax_s, (float)0.0f, CMPMODE::NE, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {1, 1, 8, 8});
        PipeBarrier<PIPE_V>();
        SetCmpMask(one_s);
        PipeBarrier<PIPE_V>();
        Select(macro_factor_s, scalar_flag, macro_factor_s, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Brcb(macro_factor_bcast, macro_factor_s, CeilDiv(valid_macros, 8), {1, 8});
        PipeBarrier<PIPE_V>();
        PipeBarrier<PIPE_V>();
        Mul<float, false>(x_float, x_float, macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        Mul<float, false>(x_float[64], x_float[64], macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();

        for (int inner_idx = 0; inner_idx < 4; inner_idx += 1) {
            int group_col0 = 32 * inner_idx;
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Abs<float, false>(macro_abs[group_col0], x_float[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            WholeReduceMax<float, false>(group_amax_s, macro_abs[group_col0], MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
            ResetMask();
            PipeBarrier<PIPE_V>();
            Muls<float, false>(group_scale_input_s, group_amax_s, (float)0.25f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            LocalTensor<uint16_t> scale_input_u16 = group_scale_input_s.ReinterpretCast<uint16_t>();
            LocalTensor<uint16_t> scale_exp_u16 = group_exp_s.ReinterpretCast<uint16_t>();
            LocalTensor<uint16_t> scale_exp_mask_u16 = exp_mask_i32.ReinterpretCast<uint16_t>();
            And<uint16_t, false>(scale_exp_u16, scale_input_u16, scale_exp_mask_u16, MASK_PLACEHOLDER, CeilDiv(2 * valid_macros, 128), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            PipeBarrier<PIPE_V>();
            Max<float, false>(group_scale_s, group_exp_s, min_scale_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            Brcb(group_scale_bcast, group_scale_s, CeilDiv(valid_macros, 8), {1, 8});
            PipeBarrier<PIPE_V>();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Div<float, false>(x_float[group_col0], x_float[group_col0], group_scale_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Abs<float, false>(macro_abs[group_col0], x_float[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(q_abs[group_col0], (float)0.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            PipeBarrier<PIPE_V>();
            SetVectorMaskByCount(32);
            Duplicate<float, false>(const_full[group_col0], (float)0.5f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            PipeBarrier<PIPE_V>();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)0.25f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)1.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)0.75f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)1.5f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)1.25f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)2.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)1.75f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)3.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)2.5f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)4.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)3.5f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)6.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)5.0f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)0.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            SetVectorMaskByCount(32);
            Muls<float, false>(neg_q_abs[group_col0], q_abs[group_col0], (float)-1.0f, MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, x_float[group_col0], (float)0.0f, CMPMODE::GE, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(macro_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            PipeBarrier<PIPE_V>();
            CompareScalar<float, uint8_t, false>(group_flag, x_float[group_col0], (float)0.0f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(neg_q_abs[group_col0], group_flag, neg_q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Add<float, false>(x_float[group_col0], macro_abs[group_col0], neg_q_abs[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Mul<float, false>(x_float[group_col0], x_float[group_col0], group_scale_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
            ResetMask();
            PipeBarrier<PIPE_V>();
        }
        Div<float, false>(y_float, x_float, macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        Div<float, false>(y_float[64], x_float[64], macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        _tmp_devent_ready_ubout_0.set();
        _tmp_devent_ready_ubout_0.wait();
        UB2GMPAD(y_macro[macro0 * 128], y_float, valid_macros, 512, 0, 0);
        PipeBarrier<PIPE_MTE3>();
        _tmp_devent_valid_ubin_0.set();
        _tmp_devent_valid_ubout_0.set();
    }
}

__aicore__ inline void mbsmxfp4_kernel_vec_bf16(GM_ADDR x_, GM_ADDR y_, GM_ADDR workspace, int rows, int cols) {
    (void)workspace;
    TPipe pipe;
    TPipe* pipe_ptr = GetTPipePtr();
    int _offset = 0;
    DEvent<PIPE_V, PIPE_MTE2, true> _tmp_devent_valid_ubin_0;
    DEvent<PIPE_MTE2, PIPE_V, false> _tmp_devent_ready_ubin_0;
    DEvent<PIPE_V, PIPE_MTE3, false> _tmp_devent_ready_ubout_0;
    DEvent<PIPE_MTE3, PIPE_V, true> _tmp_devent_valid_ubout_0;
    GlobalTensor<bfloat16_t> x; x.SetGlobalBuffer((__gm__ bfloat16_t*) x_);
    GlobalTensor<bfloat16_t> y; y.SetGlobalBuffer((__gm__ bfloat16_t*) y_);

    int macros_per_row = ((cols) / (128));
    int total_macros = macros_per_row * rows;
    GlobalTensor<bfloat16_t> x_macro = x;
    GlobalTensor<bfloat16_t> y_macro = y;
    DBuff<bfloat16_t, TPosition::VECCALC> x_bf16; x_bf16.Init(32 * 128);
    DBuff<bfloat16_t, TPosition::VECCALC> y_bf16; y_bf16.Init(32 * 128);
    LocalTensor<float> x_float = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> macro_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> q_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> neg_q_abs = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> const_full = AllocateLocalTensor<TPosition::VECCALC, float>(33 * 128);
    LocalTensor<float> macro_left_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_right_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_amax_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_safe_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_recip_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_factor_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> macro_factor_bcast = AllocateLocalTensor<TPosition::VECCALC, float>(32 * 8);
    LocalTensor<float> group_amax_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_input_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_exp_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> group_scale_bcast = AllocateLocalTensor<TPosition::VECCALC, float>(32 * 8);
    LocalTensor<uint8_t> scalar_flag = AllocateLocalTensor<TPosition::VECCALC, uint8_t>(1 * 64);
    LocalTensor<uint8_t> group_flag = AllocateLocalTensor<TPosition::VECCALC, uint8_t>(33 * 512);
    LocalTensor<float> one_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> six_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<float> min_scale_s = AllocateLocalTensor<TPosition::VECCALC, float>(1 * 64);
    LocalTensor<int> exp_mask_i32 = AllocateLocalTensor<TPosition::VECCALC, int>(1 * 64);
    int n_tiles = CeilDiv(total_macros, 32);
    int tiles_per_core = CeilDiv(n_tiles, GetBlockNum());
    int tile_begin = tiles_per_core * GetBlockIdx();
    int tile_end = Min(tile_begin + tiles_per_core, n_tiles);
    Duplicate<float, false>(one_s, (float)1.0f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<float, false>(six_s, (float)6.0f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<float, false>(min_scale_s, (float)5.877471754111438e-39f, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    Duplicate<int, false>(exp_mask_i32, (int)2139095040, MASK_PLACEHOLDER, CeilDiv(64, 64), 1, 0);
    for (int tile_idx = tile_begin; tile_idx < tile_end; tile_idx += 1) {
        int macro0 = 32 * tile_idx;
        int valid_macros = Min(32, -macro0 + total_macros);
        _tmp_devent_valid_ubin_0.wait();
        GM2UBPAD(x_bf16.get(tile_idx), x_macro[macro0 * 128], valid_macros, 256, 0, 0);
        _tmp_devent_ready_ubin_0.set();
        _tmp_devent_ready_ubin_0.wait();
        _tmp_devent_valid_ubout_0.wait();
        Cast<float, bfloat16_t, false>(x_float, x_bf16.get(tile_idx), RoundMode::CAST_NONE, MASK_PLACEHOLDER, 2 * valid_macros, {(uint16_t)1, (uint16_t)1, (uint16_t)8, (uint16_t)4});
        PipeBarrier<PIPE_V>();
        Abs<float, false>(macro_abs, x_float, MASK_PLACEHOLDER, 2 * valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        WholeReduceMax<float, false>(macro_left_s, macro_abs, MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
        WholeReduceMax<float, false>(macro_right_s, macro_abs[64], MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
        PipeBarrier<PIPE_V>();
        Max<float, false>(macro_amax_s, macro_left_s, macro_right_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        UB2UB(macro_safe_s, macro_amax_s, 1, CeilDiv(valid_macros, 8), CeilDiv(64 - valid_macros, 8), CeilDiv(64 - valid_macros, 8));
        PipeBarrier<PIPE_V>();
        CompareScalar<float, uint8_t, false>(scalar_flag, macro_safe_s, (float)0.0f, CMPMODE::NE, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {1, 1, 8, 8});
        PipeBarrier<PIPE_V>();
        SetCmpMask(one_s);
        PipeBarrier<PIPE_V>();
        Select(macro_safe_s, scalar_flag, macro_safe_s, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Div<float, false>(macro_recip_s, six_s, macro_safe_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        LocalTensor<uint16_t> macro_recip_u16 = macro_recip_s.ReinterpretCast<uint16_t>();
        LocalTensor<uint16_t> macro_factor_u16 = macro_factor_s.ReinterpretCast<uint16_t>();
        LocalTensor<uint16_t> macro_exp_mask_u16 = exp_mask_i32.ReinterpretCast<uint16_t>();
        LocalTensor<int> macro_recip_i32 = macro_recip_s.ReinterpretCast<int>();
        And<uint16_t, false>(macro_factor_u16, macro_recip_u16, macro_exp_mask_u16, MASK_PLACEHOLDER, CeilDiv(2 * valid_macros, 128), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        PipeBarrier<PIPE_V>();
        Div<float, false>(macro_safe_s, macro_recip_s, macro_factor_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Adds<float, false>(macro_safe_s, macro_safe_s, (float)-1.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Muls<float, false>(macro_safe_s, macro_safe_s, (float)256.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Cast<int, float, false>(macro_recip_i32, macro_safe_s, RoundMode::CAST_TRUNC, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint16_t)8, (uint16_t)8});
        PipeBarrier<PIPE_V>();
        Cast<float, int, false>(macro_safe_s, macro_recip_i32, RoundMode::CAST_ROUND, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint16_t)8, (uint16_t)8});
        PipeBarrier<PIPE_V>();
        Muls<float, false>(macro_safe_s, macro_safe_s, (float)0.00390625f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Adds<float, false>(macro_factor_s, macro_safe_s, (float)1.0f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        CompareScalar<float, uint8_t, false>(scalar_flag, macro_amax_s, (float)0.0f, CMPMODE::NE, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {1, 1, 8, 8});
        PipeBarrier<PIPE_V>();
        SetCmpMask(one_s);
        PipeBarrier<PIPE_V>();
        Select(macro_factor_s, scalar_flag, macro_factor_s, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
        PipeBarrier<PIPE_V>();
        Brcb(macro_factor_bcast, macro_factor_s, CeilDiv(valid_macros, 8), {1, 8});
        PipeBarrier<PIPE_V>();
        PipeBarrier<PIPE_V>();
        Mul<float, false>(x_float, x_float, macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        Mul<float, false>(x_float[64], x_float[64], macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();

        for (int inner_idx = 0; inner_idx < 4; inner_idx += 1) {
            int group_col0 = 32 * inner_idx;
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Abs<float, false>(macro_abs[group_col0], x_float[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            WholeReduceMax<float, false>(group_amax_s, macro_abs[group_col0], MASK_PLACEHOLDER, valid_macros, 1, 1, 16, ReduceOrder::ORDER_ONLY_VALUE);
            ResetMask();
            PipeBarrier<PIPE_V>();
            Muls<float, false>(group_scale_input_s, group_amax_s, (float)0.25f, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint16_t)1, (uint16_t)1, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            LocalTensor<uint16_t> scale_input_u16 = group_scale_input_s.ReinterpretCast<uint16_t>();
            LocalTensor<uint16_t> scale_exp_u16 = group_exp_s.ReinterpretCast<uint16_t>();
            LocalTensor<uint16_t> scale_exp_mask_u16 = exp_mask_i32.ReinterpretCast<uint16_t>();
            And<uint16_t, false>(scale_exp_u16, scale_input_u16, scale_exp_mask_u16, MASK_PLACEHOLDER, CeilDiv(2 * valid_macros, 128), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            PipeBarrier<PIPE_V>();
            Max<float, false>(group_scale_s, group_exp_s, min_scale_s, MASK_PLACEHOLDER, CeilDiv(valid_macros, 64), {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)8, (uint8_t)8, (uint8_t)8});
            PipeBarrier<PIPE_V>();
            Brcb(group_scale_bcast, group_scale_s, CeilDiv(valid_macros, 8), {1, 8});
            PipeBarrier<PIPE_V>();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Div<float, false>(x_float[group_col0], x_float[group_col0], group_scale_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Abs<float, false>(macro_abs[group_col0], x_float[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(q_abs[group_col0], (float)0.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            PipeBarrier<PIPE_V>();
            SetVectorMaskByCount(32);
            Duplicate<float, false>(const_full[group_col0], (float)0.5f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            PipeBarrier<PIPE_V>();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)0.25f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)1.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)0.75f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)1.5f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)1.25f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)2.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)1.75f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)3.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)2.5f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)4.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)3.5f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)6.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, macro_abs[group_col0], (float)5.0f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(q_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Duplicate<float, false>(const_full[group_col0], (float)0.0f, MASK_PLACEHOLDER, valid_macros, 1, 16);
            ResetMask();
            SetVectorMaskByCount(32);
            Muls<float, false>(neg_q_abs[group_col0], q_abs[group_col0], (float)-1.0f, MASK_PLACEHOLDER, valid_macros, {(uint16_t)1, (uint16_t)1, (uint8_t)16, (uint8_t)16});
            ResetMask();
            CompareScalar<float, uint8_t, false>(group_flag, x_float[group_col0], (float)0.0f, CMPMODE::GE, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(macro_abs[group_col0], group_flag, q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            PipeBarrier<PIPE_V>();
            CompareScalar<float, uint8_t, false>(group_flag, x_float[group_col0], (float)0.0f, CMPMODE::LT, MASK_PLACEHOLDER, valid_macros, {0, 1, 16, 16});
            PipeBarrier<PIPE_V>();
            SetCmpMask(const_full[group_col0]);
            PipeBarrier<PIPE_V>();
            Select(neg_q_abs[group_col0], group_flag, neg_q_abs[group_col0], valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Add<float, false>(x_float[group_col0], macro_abs[group_col0], neg_q_abs[group_col0], MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)1, (uint8_t)16, (uint8_t)16, (uint8_t)16});
            ResetMask();
            SetVectorMaskByCount(32);
            PipeBarrier<PIPE_V>();
            Mul<float, false>(x_float[group_col0], x_float[group_col0], group_scale_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
            ResetMask();
            PipeBarrier<PIPE_V>();
        }
        Div<float, false>(x_float, x_float, macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        Div<float, false>(x_float[64], x_float[64], macro_factor_bcast, MASK_PLACEHOLDER, valid_macros, {(uint8_t)1, (uint8_t)1, (uint8_t)0, (uint8_t)16, (uint8_t)16, (uint8_t)1});
        PipeBarrier<PIPE_V>();
        Cast<bfloat16_t, float, false>(y_bf16.get(tile_idx), x_float, RoundMode::CAST_ROUND, MASK_PLACEHOLDER, 2 * valid_macros, {(uint16_t)1, (uint16_t)1, (uint16_t)4, (uint16_t)8});
        _tmp_devent_ready_ubout_0.set();
        _tmp_devent_ready_ubout_0.wait();
        UB2GMPAD(y_macro[macro0 * 128], y_bf16.get(tile_idx), valid_macros, 256, 0, 0);
        PipeBarrier<PIPE_MTE3>();
        _tmp_devent_valid_ubin_0.set();
        _tmp_devent_valid_ubout_0.set();
    }
}

}  // namespace mbsmxfp4_detail

extern "C" __global__ __aicore__ void mbsmxfp4_kernel(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, int rows, int cols) {
    PipeBarrier<PIPE_ALL>();
    if ASCEND_IS_AIV {
        mbsmxfp4_detail::mbsmxfp4_kernel_vec_f32(x, y, workspace, rows, cols);
    }
}

extern "C" __global__ __aicore__ void mbsmxfp4_kernel_bf16(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, int rows, int cols) {
    PipeBarrier<PIPE_ALL>();
    if ASCEND_IS_AIV {
        mbsmxfp4_detail::mbsmxfp4_kernel_vec_bf16(x, y, workspace, rows, cols);
    }
}

void run_mbsmxfp4_kernel(uint32_t blockDim, void* stream, uint8_t* xmtx, uint8_t* out, uint8_t* workspace, int M, int N) {
    mbsmxfp4_kernel<<<blockDim, nullptr, stream>>>(xmtx, out, workspace, M, N);
}

void run_mbsmxfp4_kernel_bf16(uint32_t blockDim, void* stream, uint8_t* xmtx, uint8_t* out, uint8_t* workspace, int M, int N) {
    mbsmxfp4_kernel_bf16<<<blockDim, nullptr, stream>>>(xmtx, out, workspace, M, N);
}
